
name: Generate Mermaid Diagrams

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.mmd'
      - '**.md'
      - '.github/workflows/gen-svg-actions.yml'

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ICON_PACKAGES: '"@iconify-json/logos" "@iconify-json/mdi"'
      # 使用するDockerイメージ
      MERMAID_IMAGE: docker.io/minlag/mermaid-cli:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          **/*.mmd
          **/*.md
    
    - name: Generate Mermaid Diagrams
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: uni-3/render-mermaid-svg@v1
      with:
        input-files: ${{ steps.changed-files.outputs.all_changed_files }}
        icon-packages: ${{ env.ICON_PACKAGES }}
    # - name: Pull mermaid cli image
    #   if: steps.changed-files.outputs.any_changed == 'true'
    #   run: docker pull ${{ env.MERMAID_IMAGE }}

    # - name: Generate diagrams
    #   if: steps.changed-files.outputs.any_changed == 'true'
    #   env:
    #     CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
    #   run: |
    #     echo "Generating diagrams for changed files: $CHANGED_FILES"
    #     echo "with icons for archtecture diagrams: ${{env.ICON_PACKAGES}}"
    #     for file in ${CHANGED_FILES}; do
    #       output_file=$(echo "$file" | sed 's/\.\(mmd\|md\)$/.svg/' | sed 's/^docs\//docs\/auto_generated\//')

    #       echo "Processing $file"
    #       docker run --rm -t \
    #           -v "${{ github.workspace }}:/data" \
    #           -w "/data" \
    #           ${{ env.MERMAID_IMAGE}} \
    #           -i "$file" \
    #           -o "$output_file" \
    #           --iconPacks ${{env.ICON_PACKAGES}} \
    #           --puppeteerConfigFile /puppeteer-config.json

    #     done

    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Generate Mermaid diagrams for changed files
        file_pattern: '**/*.svg'